import { SITE, articles, categories, getArticle, getCategory, breakingNews, hotNews } from './data.js';

const app = document.querySelector('#app');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => new Intl.DateTimeFormat('ne-NP',{dateStyle:'medium'}).format(new Date(value));
const path = () => window.location.pathname.replace(/\/+$/,'') || '/';
const categoryLabel = slug => getCategory(slug)?.label || slug;
const image = (src, alt) => `<img src="${esc(src || '/favicon.svg')}" alt="${esc(alt)}" loading="lazy" width="1200" height="675" onerror="this.onerror=null;this.src='/favicon.svg';this.alt='NewsArc लोगो'">`;

function meta(title, description, url=window.location.href, imageUrl='/favicon.svg', type='website') {
  document.title = title;
  const set = (selector, attr, value) => { let el=document.head.querySelector(selector); if(!el){el=document.createElement('meta');el.setAttribute(attr,selector.includes('property')?selector.match(/property="([^"]+)/)[1]:selector.match(/name="([^"]+)/)[1]);document.head.appendChild(el)} el.content=value; };
  document.querySelector('link[rel=canonical]').href=url;
  set('meta[name="description"]','name',description); set('meta[property="og:title"]','property',title); set('meta[property="og:description"]','property',description); set('meta[property="og:url"]','property',url); set('meta[property="og:type"]','property',type); set('meta[property="og:image"]','property',imageUrl); set('meta[name="twitter:title"]','name',title); set('meta[name="twitter:description"]','name',description); set('meta[name="twitter:image"]','name',imageUrl);
  const robots=document.querySelector('meta[name="robots"]'); robots.content=path()==='/search'?'noindex,follow':'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1';
}
function schema(data){document.querySelectorAll('script[data-route-schema]').forEach(el=>el.remove());const el=document.createElement('script');el.type='application/ld+json';el.dataset.routeSchema='true';el.textContent=JSON.stringify(data);document.head.appendChild(el)}
function header(){return `<div class="topline"><div class="wrap"><span>विश्वसनीय जानकारी • स्पष्ट सन्दर्भ • मानवीय सम्पादन</span><span>${new Date().toLocaleDateString('ne-NP',{dateStyle:'long'})}</span></div></div><header class="site-header"><div class="wrap head-row"><a href="/" class="brand" aria-label="NewsArc गृहपृष्ठ">NEWSARC<small>${SITE.tagline}</small></a><div class="actions"><button class="icon-btn" id="theme" aria-label="रङ्ग मोड बदल्नुहोस्">◐</button><button class="menu-btn mobile-only" id="menu" aria-expanded="false" aria-controls="primary-nav">☰</button></div></div><nav class="nav" id="primary-nav" aria-label="मुख्य नेभिगेसन"><ul class="wrap"><li><a href="/">गृहपृष्ठ</a></li><li><a href="/latest">नयाँ</a></li>${categories.map(c=>`<li><a href="/${c.slug}">${c.icon} ${c.label}</a></li>`).join('')}<li><a href="/search">खोज्नुहोस्</a></li></ul></nav></header>`}
function footer(){return `<footer class="site-footer"><div class="wrap footer-grid"><div><h2>NEWSARC</h2><p>${SITE.tagline}<br>नेपाल र विश्वका समाचार तथा उपयोगी व्याख्या।</p></div><div><h3>NewsArc</h3><a href="/about">हाम्रो बारेमा</a><a href="/contact">सम्पर्क</a><a href="/editorial-policy">सम्पादकीय नीति</a><a href="/corrections">सुधार नीति</a></div><div><h3>नीति</h3><a href="/privacy-policy">गोपनीयता</a><a href="/terms">प्रयोगका सर्त</a><a href="/disclaimer">अस्वीकरण</a></div></div><div class="wrap copyright">© ${new Date().getFullYear()} NewsArc. तथ्य जाँच र मानवीय सम्पादन आवश्यक हुन्छ।</div></footer>`}
function card(a){return `<article class="card"><a href="/news/${a.category}/${a.slug}">${image(a.image,a.title)}<div class="card-body"><span class="label">${esc(categoryLabel(a.category))}</span><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><span class="meta">${date(a.publishedAt)} · ${esc(a.author)}</span><span class="read">पूरा पढ्नुहोस् →</span></div></a></article>`}
function home(){meta('NewsArc — आजको खबर, आजै','नेपाल र विश्वका समाचार, उपयोगी व्याख्या र जिम्मेवार जानकारी।',SITE.url+'/');const latest=[...articles].sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt));return `<main id="main-content"><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">NEWSARC</span><h1>आजको खबर,<br>आजै बुझौं।</h1><p>समाचारसँगै सन्दर्भ, स्रोत र उपयोगी व्याख्या। अपुष्ट दाबीलाई समाचारका रूपमा प्रस्तुत नगर्ने हाम्रो प्रतिबद्धता।</p></div><form class="search" action="/search" method="get"><input name="q" aria-label="समाचार खोज्नुहोस्" placeholder="समाचार, विषय वा वर्ग खोज्नुहोस्"><button>खोज्नुहोस्</button></form></div></section><div class="wrap"><section class="section"><div class="section-head"><h2>🔴 BREAKING NEWS</h2><p>सम्पादकीय रूपमा पुष्टि भएपछि मात्र</p></div><div class="alert">${breakingNews.length ? breakingNews.map(esc).join(' · ') : 'अहिले कुनै अपुष्ट वा अपूर्ण सूचनालाई ब्रेकिङका रूपमा प्रस्तुत गरिएको छैन। नयाँ अपडेटका लागि NewsArc जाँच गरिरहनुहोस्।'}</div></section><section class="section"><div class="section-head"><h2>🔥 HOT NEWS</h2><p>महत्त्वपूर्ण र प्रमाणित सामग्री</p></div>${hotNews.length?`<div class="feature">${hotNews.map(slug=>getArticle(slug)).filter(Boolean).map(card).join('')}</div>`:'<div class="empty">सम्पादकीय टोलीले महत्त्वपूर्ण सामग्री पुष्टि गरेपछि यो स्थानमा देखिनेछ।</div>'}</section><section class="section"><div class="section-head"><h2>🕐 LATEST NEWS</h2><a class="read" href="/latest">सबै हेर्नुहोस् →</a></div><div class="grid">${latest.slice(0,6).map(card).join('')}</div></section><section class="section split"><div><div class="section-head"><h2>📈 TRENDING</h2></div><ol class="ranked">${latest.slice(0,5).map((a,i)=>`<li><span class="rank">${String(i+1).padStart(2,'0')}</span><a href="/news/${a.category}/${a.slug}"><strong>${esc(a.title)}</strong><small class="meta">${categoryLabel(a.category)} · ${date(a.publishedAt)}</small></a></li>`).join('')}</ol></div><div><div class="section-head"><h2>वर्गहरू</h2></div><div class="category-grid">${categories.map(c=>`<a class="category-link" href="/${c.slug}">${c.icon} ${c.label}</a>`).join('')}</div></div></section></div></main>`}
function listing(title, list, desc){meta(`${title} — NewsArc`,desc,`${SITE.url}${window.location.pathname}`);return `<main id="main-content" class="wrap"><section class="section"><div class="section-head"><div><span class="eyebrow">NEWSARC</span><h1>${title}</h1><p>${desc}</p></div></div><div class="grid">${list.length?list.map(card).join(''):'<div class="empty">यो वर्गमा अहिले प्रकाशित सामग्री छैन।</div>'}</div></section></main>`}
function articlePage(a){const url=`${SITE.url}/news/${a.category}/${a.slug}`;meta(`${a.title} — NewsArc`,a.summary,url,a.image,'article');schema({'@context':'https://schema.org','@type':'NewsArticle','headline':a.title,'description':a.summary,'image':[`${SITE.url}${a.image}`],'datePublished':a.publishedAt,'dateModified':a.updatedAt||a.publishedAt,'author':{'@type':'Organization','name':a.author},'publisher':{'@type':'Organization','name':'NewsArc','url':SITE.url},'mainEntityOfPage':{'@type':'WebPage','@id':url}});const related=articles.filter(x=>x.slug!==a.slug&&(x.category===a.category||x.tags.some(t=>a.tags.includes(t)))).slice(0,3);return `<main id="main-content"><article class="article"><nav class="breadcrumbs" aria-label="ब्रेडक्रम्ब"><a href="/">गृहपृष्ठ</a> / <a href="/${a.category}">${categoryLabel(a.category)}</a> / ${esc(a.title)}</nav><span class="label">${categoryLabel(a.category)}</span><h1>${esc(a.title)}</h1><p class="deck">${esc(a.summary)}</p><p class="byline">लेखक: ${esc(a.author)} · प्रकाशित: ${date(a.publishedAt)}${a.updatedAt&&a.updatedAt!==a.publishedAt?` · अद्यावधिक: ${date(a.updatedAt)}`:''}</p>${image(a.image,a.title)}<div class="article-copy">${a.content.map(([h,p])=>`<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('')}</div><div class="share"><strong>सेयर गर्नुहोस्:</strong><button data-share="whatsapp">WhatsApp</button><button data-share="facebook">Facebook</button><button data-share="x">X</button><button data-share="copy">लिङ्क कपी</button></div><p class="meta">स्रोत/सम्पादकीय टिप्पणी: यो NewsArc को मूल व्याख्यात्मक सामग्री हो। वर्तमान समाचारमा आधिकारिक स्रोत र मिति जाँचेर मात्र थप अपडेट प्रकाशित गरिन्छ।</p><section class="related"><h2>सम्बन्धित समाचार</h2><div class="grid">${related.length?related.map(card).join(''):'<p class="empty">सम्बन्धित सामग्री थपिँदैछ।</p>'}</div></section></article></main>`}
function legal(slug){const pages={about:['NewsArc बारेमा','NewsArc नेपाल र विश्वका विषयमा स्पष्ट समाचार, उपयोगी व्याख्या र सार्वजनिक जानकारी प्रस्तुत गर्ने डिजिटल प्रकाशन हो। हामी प्रकाशनअघि तथ्य, मिति र स्रोत जाँच्ने प्रयास गर्छौं।'],contact:['सम्पर्क','सम्पादकीय सुझाव, तथ्य सुधार वा स्रोतसम्बन्धी प्रश्नका लागि NewsArc सम्पादकीय टोलीलाई सम्पर्क गर्नुहोस्। इमेल: editorial@newsarc.example (यो ठेगाना प्रकाशित गर्नुअघि वास्तविक सम्पर्क ठेगाना राख्नुहोस्)।'], 'editorial-policy':['सम्पादकीय नीति','हामी अपुष्ट दाबीलाई तथ्यका रूपमा प्रस्तुत गर्दैनौं। सामग्रीमा स्पष्ट शीर्षक, प्रकाशन मिति, लेखक र आवश्यक सन्दर्भ राखिन्छ। गल्ती भेटिएमा सुधार नीति अनुसार नोट गरिन्छ।'],corrections:['सुधार नीति','गलत वा अपूर्ण जानकारी भेटिएमा प्रमाणसहित सम्पर्क गर्नुहोस्। पुष्टि भएपछि सामग्रीमा स्पष्ट सुधार वा अद्यावधिक गरिन्छ।'], 'privacy-policy':['गोपनीयता नीति','NewsArc आवश्यक सेवा सञ्चालनका लागि न्यूनतम प्राविधिक जानकारी प्रयोग गर्न सक्छ। हामी व्यक्तिगत जानकारी बेच्दैनौं। विश्लेषण वा विज्ञापन जोडिएमा त्यसको जानकारी यस नीतिमा अद्यावधिक गरिनेछ।'],terms:['प्रयोगका सर्त','NewsArc सामग्री जानकारीका लागि हो। सामग्रीको पुनःप्रयोग गर्दा स्रोत र लिङ्क उल्लेख गर्नुहोस्। गैरकानुनी, भ्रामक वा हानिकारक प्रयोग निषेध छ।'],disclaimer:['अस्वीकरण','समाचार र व्याख्याहरू सामान्य जानकारीका लागि हुन्। महत्त्वपूर्ण निर्णयअघि सम्बन्धित आधिकारिक निकाय वा विशेषज्ञको सल्लाह लिनुहोस्।']};const [title,body]=pages[slug]||['पृष्ठ भेटिएन','तपाईंले खोजेको पृष्ठ उपलब्ध छैन।'];meta(`${title} — NewsArc`,body,`${SITE.url}/${slug}`);return `<main id="main-content" class="page"><span class="eyebrow">NEWSARC</span><h1>${title}</h1><p>${body}</p><p>अन्तिम अद्यावधिक: ${new Date().toLocaleDateString('ne-NP',{dateStyle:'long'})}</p></main>`}
function search(){const q=new URLSearchParams(location.search).get('q')?.trim()||'';const results=q?articles.filter(a=>`${a.title} ${a.summary} ${a.category} ${a.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase())):[];meta('समाचार खोज — NewsArc','NewsArc का समाचार खोज्नुहोस्.',`${SITE.url}/search`);return `<main id="main-content" class="wrap"><section class="section"><h1>समाचार खोज्नुहोस्</h1><form class="search" id="search-form"><input name="q" value="${esc(q)}" placeholder="विषय, शीर्षक वा वर्ग"><button>खोज्नुहोस्</button></form><p class="meta">${q?`${results.length} वटा परिणाम`: 'खोज्नका लागि शब्द लेख्नुहोस्।'}</p><div class="grid">${results.map(card).join('')|| (q?'<div class="empty">कुनै परिणाम भेटिएन। फरक शब्द वा वर्गको नाम प्रयोग गर्नुहोस्।</div>':'')}</div></section></main>`}
function render(){const p=path();let body;if(p==='/')body=home();else if(p==='/latest')body=listing('नयाँ समाचार',[...articles].sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)),'NewsArc मा प्रकाशित पछिल्ला सामग्री।');else if(p==='/search')body=search();else if(p.startsWith('/news/')){const parts=p.split('/');const a=getArticle(parts.at(-1));body=a?articlePage(a):legal('missing');}else if(getCategory(p.slice(1))) {const c=getCategory(p.slice(1));body=listing(`${c.icon} ${c.label}` ,articles.filter(a=>a.category===c.slug),`${c.label} सम्बन्धी NewsArc सामग्री।`);}else body=legal(p.slice(1));app.innerHTML=header()+body+footer();document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===p)a.setAttribute('aria-current','page')});document.querySelector('#theme')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('newsarc-theme',document.body.classList.contains('dark')?'dark':'light')});document.querySelector('#menu')?.addEventListener('click',e=>{const n=document.querySelector('.nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});document.querySelector('#search-form')?.addEventListener('submit',e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q');history.pushState({},'',`/search${q?`?q=${encodeURIComponent(q)}`:''}`);render()});document.querySelectorAll('[data-share]').forEach(b=>b.addEventListener('click',()=>{const u=encodeURIComponent(location.href),t=encodeURIComponent(document.title);const urls={whatsapp:`https://wa.me/?text=${t}%20${u}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${u}`,x:`https://x.com/intent/post?text=${t}&url=${u}`};if(b.dataset.share==='copy')navigator.clipboard?.writeText(location.href).then(()=>b.textContent='कपी भयो');else window.open(urls[b.dataset.share],'_blank','noopener,noreferrer')}));}
if(localStorage.getItem('newsarc-theme')==='dark')document.body.classList.add('dark');window.addEventListener('popstate',render);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
