export const SITE={name:'NewsArc',tagline:'News that makes sense',taglineNe:'आजको खबर, आजै',url:'https://newsarc-ga3f.vercel.app',author:'NewsArc Editorial Team'};
export const categories=[
 {slug:'nepal',en:'Nepal',ne:'नेपाल',icon:'🇳🇵',image:'/images/nepal.svg'},
 {slug:'politics',en:'Politics',ne:'राजनीति',icon:'🏛️',image:'/images/politics.svg'},
 {slug:'business',en:'Business',ne:'बिजनेस',icon:'💰',image:'/images/business.svg'},
 {slug:'technology',en:'Technology',ne:'प्रविधि',icon:'💻',image:'/images/technology.svg'},
 {slug:'sports',en:'Sports',ne:'खेलकुद',icon:'⚽',image:'/images/sports.svg'},
 {slug:'world',en:'World',ne:'विश्व',icon:'🌎',image:'/images/world.svg'},
 {slug:'education',en:'Education',ne:'शिक्षा',icon:'🎓',image:'/images/education.svg'},
 {slug:'entertainment',en:'Entertainment',ne:'मनोरञ्जन',icon:'🎬',image:'/images/entertainment.svg'}
];
// Static, human-edited content. Add verified stories here; no database or feed is required.
export const articles=[
 {slug:'safe-online-news-reading',category:'technology',title:'How to check a news story before you share it',titleNe:'अनलाइन समाचार पढ्दा स्रोत र मिति कसरी जाँच्ने?',summary:'A practical guide to checking the source, date, author and evidence behind an online claim.',summaryNe:'अनलाइन दाबीको स्रोत, मिति, लेखक र प्रमाण जाँच्ने व्यावहारिक मार्गदर्शन।',image:'/images/technology.svg',author:'NewsArc Editorial Team',publishedAt:'2026-09-24T08:00:00+05:45',updatedAt:'2026-09-24T08:00:00+05:45',tags:['media literacy','technology'],content:[['What to check','Look for the publisher, author, publication date and original source. For important claims, compare more than one credible source.'],['Why it matters','Old reports can look like new events when they are reposted without context. Reading beyond the headline helps prevent accidental misinformation.'],['NewsArc editorial note','NewsArc prioritizes clear facts, context and attribution. Unverified claims are not presented as confirmed breaking news.']]},
 {slug:'digital-safety-basics',category:'technology',title:'Five simple digital-safety habits to start today',titleNe:'डिजिटल सु���क्षा: आजै अपनाउन सकिने पाँच सरल अभ्यास',summary:'Practical basics for stronger passwords, two-step verification and spotting phishing attempts.',summaryNe:'बलियो पासवर्ड, दुई-चरण प्रमाणीकरण र फिसिङ पहिचानका आधारभूत उपाय।',image:'/images/technology.svg',author:'NewsArc Editorial Team',publishedAt:'2026-09-23T09:30:00+05:45',updatedAt:'2026-09-23T09:30:00+05:45',tags:['cybersecurity','technology'],content:[['Use strong, unique passwords','Use a different long password for every service. A reputable password manager can make this easier.'],['Turn on two-step verification','Add two-step verification to email, social and financial accounts for an additional layer of protection.'],['Check links before opening','Be cautious with urgent messages, prizes and requests for money. Check the sender and domain before clicking.']]},
 {slug:'student-ai-use-guide',category:'education',title:'What students should know before using AI tools',titleNe:'विद्यार्थीले AI उपकरण प्रयोग गर्दा ध्यान दिनुपर्ने कुरा',summary:'How to use AI as a learning aid while checking facts, protecting privacy and keeping work original.',summaryNe:'तथ्य जाँच, गोपनीयता र मौलिकता कायम राख्दै AI लाई सिकाइमा प्रयोग गर्ने तरिका।',image:'/images/education.svg',author:'NewsArc Editorial Team',publishedAt:'2026-09-22T10:00:00+05:45',updatedAt:'2026-09-22T10:00:00+05:45',tags:['education','AI'],content:[['Use it as an aid','AI can help explain a topic or generate practice questions, but students should check answers and sources themselves.'],['Protect privacy','Do not upload personal information, sensitive school documents or someone else’s private data.'],['Keep work original','Use your own understanding, citations and judgment instead of submitting generated text unchanged.']]},
 {slug:'household-budget-basics',category:'business',title:'A simple way to start a household budget',titleNe:'घरायसी बजेट बनाउन सुरु गर्ने सरल तरिका',summary:'A practical starting point for organizing income, essential spending, saving and emergencies.',summaryNe:'आम्दानी, आवश्यक खर्च, बचत र आकस्मिक खर्च व्यवस्थित गर्ने सरल सुरुवात।',image:'/images/business.svg',author:'NewsArc Editorial Team',publishedAt:'2026-09-21T08:30:00+05:45',updatedAt:'2026-09-21T08:30:00+05:45',tags:['personal finance','business'],content:[['Start with real numbers','Write down one month of income and regular expenses. Actual bills and records are more useful than guesses.'],['Separate needs from wants','Put housing, food, health and education first, then plan savings and optional spending from what remains.'],['Start small and adjust','A regular small saving habit can help with unexpected costs. Adjust the plan to your income and responsibilities.']]},
 {slug:'community-sports-coverage',category:'sports',title:'Why local sports coverage matters to communities',titleNe:'स्थानीय खेलकुद समाचारले समुदायलाई कसरी जोड्छ?',summary:'Local competitions and athletes can show how sport creates health, discipline and community participation.',summaryNe:'स्थानीय प्रतियोगिता र खेलाडीले स्वास्थ्य, अनुशासन र सामुदायिक सहभागिता कसरी बढाउँछन्?',image:'/images/sports.svg',author:'NewsArc Editorial Team',publishedAt:'2026-09-20T11:00:00+05:45',updatedAt:'2026-09-20T11:00:00+05:45',tags:['sports','community'],content:[['More than a score','Local sport creates opportunities for health, discipline and participation. Coverage should recognize athletes, coaches and organizers.'],['Facts matter','Scores, dates and competition names should be checked with official organizers or teams before publication.'],['Make coverage inclusive','Giving women, youth and underrepresented athletes fair attention is part of responsible sports journalism.']]},
 {slug:'public-information-checklist',category:'nepal',title:'A checklist for reading important public notices',titleNe:'महत्त्वपूर्ण सार्वजनिक सूचना पढ्दा उपयोगी जाँचसूची',summary:'The first details to check when a government notice or public announcement affects a service or community.',summaryNe:'सरकारी सूचना वा सार्वजनिक घोषणाले सेवा र समुदायलाई असर गर्दा जाँच्नुपर्ने मुख्य विवरण।',image:'/images/nepal.svg',author:'NewsArc Editorial Team',publishedAt:'2026-09-19T07:45:00+05:45',updatedAt:'2026-09-19T07:45:00+05:45',tags:['Nepal','public information'],content:[['Check the agency and date','Identify which agency issued the notice and when it was published.'],['Understand its scope','A notice may apply only to a district, service, institution or group rather than the whole country.'],['Keep the original notice','Prefer the official website or notice number over an isolated social-media screenshot.']]}
];
export const breakingNews=[];export const hotNews=[];export const getArticle=slug=>articles.find(a=>a.slug===slug);export const getCategory=slug=>categories.find(c=>c.slug===slug);
